// Generated by CoffeeScript 1.6.3
angular.module('demo2App').controller('LoginCtrl', function($scope, $state, auth) {
  $scope.login = function() {
    var toState;
    toState = $scope.toState;
    $scope.toState = null;
    return auth.login({
      username: $scope.login.username,
      password: $scope.login.password
    }, function(user, error) {
      if (error) {
        console.log(error);
      }
      if (user) {
        console.log(user);
      }
      console.log("toState: " + $scope.toState);
      return $state.transitionTo(toState);
    });
  };
  return $scope.logout = function() {
    console.log("Logout!");
    auth.logout;
    return $state.transitionTo('main');
  };
});
