// Generated by CoffeeScript 1.6.3
var passport, users;

passport = require("passport");

users = require('../controllers/users');

module.exports = function(app) {
  var auth;
  auth = passport.authenticate('basic', {
    session: false
  });
  app.get('/api/auth', auth, users.auth);
  app.get('/api/users', auth, users.list);
  return app.post('/api/users', users.create);
};
