// Generated by CoffeeScript 1.6.3
(function() {
  var users;

  users = require('../controllers/users');

  module.exports = function(app) {
    return app.get('/api/auth', users.auth);
  };

}).call(this);
