// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    development: {
      app: {
        name: 'Peacemakers (dev)'
      },
      db: 'mongodb://localhost/peacemakers-dev'
    }
  };

}).call(this);
