// Generated by CoffeeScript 1.6.3
var LocalStrategy, User, mongoose;

mongoose = require('mongoose');

LocalStrategy = require('passport-local').Strategy;

User = mongoose.model('User');

module.exports = function(passport, config) {
  var localStrategy;
  localStrategy = new LocalStrategy({
    usernameField: 'username',
    passwordField: 'password'
  });
  return passport.use(localStrategy, function(username, password, done) {
    if (err) {
      return done(err);
    }
    if (!user) {
      return done(null, false, {
        message: 'Unknown User'
      });
    }
    if (!user.authenticate(password)) {
      return done(null, false, {
        message: 'Invalid Password'
      });
    }
    return done(null, user);
  });
};
