// Generated by CoffeeScript 1.6.3
var BasicStrategy, User, mongoose;

mongoose = require('mongoose');

BasicStrategy = require('passport-http').BasicStrategy;

User = mongoose.model('User');

module.exports = function(passport, config) {
  return passport.use(new BasicStrategy(function(username, password, done) {
    return User.findOne({
      username: username
    }, function(err, user) {
      if (err) {
        return done(err);
      }
      if (!user) {
        return done(null, false, {
          message: 'Unknown User'
        });
      }
      if (!user.authenticate(password)) {
        return done(null, false, {
          message: 'Invalid Password'
        });
      }
      return done(null, user);
    });
  }));
};
