// Generated by CoffeeScript 1.6.3
(function() {
  var app, config, env, exports, express, mongoose, passport, routes, schools, users;

  express = require('express');

  passport = require('passport');

  routes = require('./routes');

  env = process.env.NODE_ENV || 'development';

  config = require('./config/config')[env];

  mongoose = require('mongoose');

  mongoose.connect(config.db);

  require("./models/user");

  require("./models/school");

  require('./config/passport')(passport, config);

  app = express();

  app.use(express.bodyParser());

  app.use(passport.initialize());

  users = require('./routes/users');

  users(app);

  schools = require('./routes/schools');

  schools(app);

  app.get('/api/awesomeThings', routes.awesomeThings);

  app.use(function(req, res) {
    return res.json({
      'ok': false,
      'status': '404'
    });
  });

  exports = module.exports = app;

}).call(this);
