// Generated by CoffeeScript 1.6.3
var RoleSchema, Schema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

RoleSchema = new Schema({
  name: {
    type: String,
    "default": ''
  },
  displayName: String,
  description: String,
  permissions: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Permission'
    }
  ]
});

mongoose.model('Role', RoleSchema);
