// Generated by CoffeeScript 1.6.3
(function() {
  var Schema, SchoolSchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  SchoolSchema = new Schema({
    name: {
      type: String,
      "default": ''
    },
    www: {
      type: String,
      "default": ''
    },
    createdAt: {
      type: Date,
      "default": Date.now
    }
  });

  mongoose.model('School', SchoolSchema);

}).call(this);
