// Generated by CoffeeScript 1.6.3
angular.module("demo2App").factory('auth', function($cookieStore, $http, Base64) {
  var currentUser;
  currentUser = $cookieStore.get("user") || {
    username: "",
    token: "",
    permissions: [
      {
        subject: '',
        action: ''
      }
    ]
  };
  $cookieStore.remove("user");
  return {
    authorize: function(accessLevel, permissions) {
      var action, p, permission, subject, _i, _len;
      if (permissions === void 0) {
        permissions = currentUser.permissions;
      }
      permission = accessLevel.split(":");
      subject = permission[0];
      action = permission[1];
      for (_i = 0, _len = permissions.length; _i < _len; _i++) {
        p = permissions[_i];
        if (p.subject === subject && p.action === action) {
          return true;
        }
        if (p.subject === '*' || p.action === '*') {
          return true;
        }
      }
      return false;
    },
    login: function(user) {
      console.log(user);
      return $http.defaults.headers.common['Authorization'] = 'Basic ' + Base64.encode(user.username + ':' + user.password);
    },
    isLoggedIn: function() {
      console.log(currentUser);
      if (currentUser.token) {
        return true;
      }
      return false;
    }
  };
});
