// Generated by CoffeeScript 1.6.3
var User, mongoose, passport;

passport = require('passport');

mongoose = require('mongoose');

User = mongoose.model('User');

exports.auth = function(req, res) {
  console.log("GET: ");
  console.log(req);
  return School.find().exec(function(err, schools) {
    if (!err) {
      return res.send(schools);
    } else {
      return console.log(err);
    }
  });
};
