// Generated by CoffeeScript 1.6.3
var User, mongoose;

mongoose = require('mongoose');

User = mongoose.model('User');

exports.list = function(req, res) {
  console.log("GET: ");
  console.log(req.query);
  console.log(req.authInfo);
  return User.find().exec(function(err, users) {
    if (!err) {
      return res.send(users);
    } else {
      return console.log(err);
    }
  });
};

exports.create = function(req, res) {
  var user;
  console.log("POST: ");
  console.log(req.body);
  user = new User(req.body);
  user.save(function(err) {
    if (!err) {
      return console.log("created");
    } else {
      return console.log(err);
    }
  });
  return res.send(user);
};
