// Generated by CoffeeScript 1.6.3
(function() {
  var mongoose, request, should;

  should = require("should");

  request = require("supertest");

  mongoose = require("mongoose");

  describe("SchoolsAPI", function() {
    var url;
    url = "http://localhost:9001";
    before(function(done) {
      mongoose.connect("mongodb://localhost/peacemakers-dev");
      return done();
    });
    return it("POST a new School", function(done) {
      var school;
      school = {
        name: "Test School 1",
        www: "www.testschool1.edu.mx"
      };
      return request(url).post("/api/schools").send(school).expect('Content-Type', /json/).expect(200).end(function(err, res) {
        if (err) {
          throw done(err);
        }
        res.body.should.have.property('_id');
        res.body.name.should.equal('Test School 1');
        res.body.www.should.equal('www.testschool1.edu.mx');
        res.body.createdAt.should.not.equal(null);
        return done();
      });
    });
  });

}).call(this);
