// Generated by CoffeeScript 1.6.3
var User, app, mongoose, request, should;

mongoose = require("mongoose");

request = require("supertest");

should = require("should");

app = require("../../server/main");

User = mongoose.model('User');

describe("User Model", function() {
  return it("should register a new User", function(done) {
    this.user = new User({
      username: "test",
      password: "password",
      email: "test@mail.com"
    });
    this.user.save(function(err) {
      if (err) {
        return done(err);
      }
    });
    return done();
  });
});
