// Generated by CoffeeScript 1.6.3
angular.module('demo2App', ['ui.router', 'ngCookies', 'ngBase64']).config(function($stateProvider, $urlRouterProvider, $locationProvider) {
  $urlRouterProvider.otherwise('/404');
  $stateProvider.state('main', {
    url: "/",
    templateUrl: 'views/main.html',
    controller: 'MainCtrl',
    access: '*:*'
  }).state('school', {
    url: "/school",
    templateUrl: 'views/school.html',
    controller: 'SchoolCtrl',
    access: 'schools:*'
  }).state('login', {
    url: "/login",
    templateUrl: 'views/login.html',
    controller: 'LoginCtrl',
    access: '*:*'
  }).state('logout', {
    url: "/logout",
    controller: 'LoginCtrl',
    access: '*:*'
  }).state('not_found', {
    url: "/404",
    templateUrl: '404.html',
    access: '*:*'
  });
  return $locationProvider.html5Mode(true);
}).run(function($state, $rootScope, auth) {
  $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
    console.log("StateChangeStart from: " + fromState.url + " to: " + toState.url);
    $rootScope.error = null;
    if (toState.access !== '*:*' && !auth.isLoggedIn()) {
      event.preventDefault();
      $rootScope.toState = toState.name;
      return $state.transitionTo('login');
    }
    /*
    if toState.name is not 'login'
      if not auth.authorize toState.access
        if auth.isLoggedIn()
          $state.go 'main'
        else
          console.log ">> Login"
          $state.go 'login'
    */

  });
  return $rootScope.$on('$stateChangeSuccess', function() {
    return $rootScope.doingResolve = false;
  });
});
