// Generated by CoffeeScript 1.6.3
angular.module('demo2App', ['ui.router', 'ngCookies']).config(function($stateProvider, $urlRouterProvider, $locationProvider) {
  $urlRouterProvider.otherwise('/404');
  $stateProvider.state('main', {
    url: "/",
    templateUrl: 'views/main.html',
    controller: 'MainCtrl',
    access: '*:*'
  }).state('login', {
    url: "/login",
    templateUrl: 'views/login.html',
    controller: 'LoginCtrl',
    access: '*:*'
  }).state('school', {
    url: "/school",
    templateUrl: 'views/school.html',
    controller: 'SchoolCtrl',
    access: 'schools:*'
  }).state('not_found', {
    url: "/404",
    templateUrl: '404.html',
    access: '*:*'
  });
  return $locationProvider.html5Mode(true);
}).run(function($state, $rootScope, auth) {
  $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
    console.log(toState);
    console.log("StateChangeStart from: " + fromState.url + " to: " + toState.url);
    $rootScope.doingResolve = true;
    $rootScope.error = null;
    if (toState.name === !'login') {
      if (!auth.authorize(toState.access)) {
        if (auth.isLoggedIn()) {
          return $state.go('main');
        } else {
          console.log(">> Login");
          return $state.go('login');
        }
      }
    }
  });
  return $rootScope.$on('$stateChangeSuccess', function() {
    $rootScope.doingResolve = false;
    return console.log('StateChangeSuccess');
  });
});
